### ISSUE TITLE
Show info to match candy/pokemon needed

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#101]
This is a little tweak you would be able to do with the data already available in the software. My suggestion is to show a bit more information to the user for the following 2 cases:
-If the user has more pokemon than candy necessary to evolve them, the software could show in Candy column (in a tooltip for example, or in brackets in a greyer colour) how many more candies it needs to be able to evolve all the pokemon of each species. So if I have 10 pidgies and 108 candies, the software would show +12.
-If the user has more candies than pokemon necessary to use them, the software could show in Count column  (in a tooltip or in brackets in a greyer colour) how many more Pokemon it needs of each species to be able to use all the candies. So if I have 120 candies and 8 pidgies, the software would show +2. (only round numbers of course)

I think it would be a nice piece of info, this way I can focus my efforts on capturing the pokemon I need for my next mass evolve.

Edit: correct mistakes.

**Comment by vlechemin** [comment]
![image](https://cloud.githubusercontent.com/assets/638315/17931964/132c4a0c-6a0e-11e6-95ec-cfc9ef42993a.png)

I made this for my own need, if other people find it useful, I could make a pull request

**Comment by vinnymac** [comment]
@vlechemin I think the additional info belongs in a tooltip explaining what it means exactly for our users. #124 will add tooltips to a lot of things and then maybe you could do a PR for these changes as tooltips.

**Comment by iPaulis** [comment]
@vlechemin to make it visually easier to understand, if there are more candies than pidgies to use them I wouldnt show "/168" in candy column, I would only show +14 in evolves column.
And in the opposite case, if there are more rattatas than candies needed to evolve them, I wouldnt show "14/" in evolves column (I mean, of course they are 14, you have the same number in count column), I would only show +77 in candy column. This way you now how many candies left to evolve all rattatas in count column.

**Comment by vlechemin** [comment]
@vinnymac tooltips are great, but I think it's nice to see directly which Pokemons are ready to be evolved, and which are missing before using an egg (btw I tried evolving from the app, but it did not work :( not sure if I misused it or if it's a bug):

```
[1] [+] Retrieving player's Pokemons and Calculating Evolves
[1] [+] Retrieving player info
[1] [+] Evolved Pokemon with id: undefined
[1] [+] Evolved Pokemon with id: undefined
[1] [+] Evolved Pokemon with id: undefined
```

@iPaulis I see your point for 338/168, but for for 14/10, I think it's a difference of point of view :)
It means you have all necessary Rattatas for the number of candies you have and you can even sell 4 if you want to, maybe it could be written as 10/10 +4 ? But it does not look right

**Comment by iPaulis** [comment]
You could just write 10 +4, or 10 (+4). Anyway, I still dont understand why you need the +4 part if you already have that number in count column (and you dont have enough candies). The evolvable pokemon are 10, the total pokemon are 14, both numbers are in their own columns. 14-10 = 4, but I dont see the need for this if you dont even have enough candies to evolve them, and if you do have more candies, then it is the pidgey case.

**Comment by mackhankins** [comment]
@vlechemin good catch on evolves #126

**Comment by vlechemin** [comment]
@iPaulis quicker to look only at 1 column, as I said I think it's a preference thing :)

**Comment by vinnymac** [comment]
@vlechemin I understand the need to get information asap. So maybe we will add a feature toggle for revealing more information in the table. If we used more CSS we could have the table scale to less information as the screen got smaller, but that is another task for someone else right now. I think the tooltips are really useful, but I see your point. With that said I think both your solution and the tooltips could be used in unison.

The issue you described is now fixed as of v1.3.2.

**Comment by YesThatAllen** [comment]
I'd love to see this as well.. knowing how many more candies i need for an evolution can help me plan who I pick as my next buddy, and which I should be on the lookout for (ie I might skip catching that lame Spearow unless I that I was just 4 away from being able to evolve one).

Having this in the same column seems ideal.. instead of just showing `46` in the candy column, showing `46/50` would let me see how far til the next evolution.

**Comment by YesThatAllen** [comment]
I'm having a hard time with the numbers shown. 

I'm seeing 


27 Pidgey
276 Candy `+48`	
23 Evolves

If I want to evolve 27 candy in a single lucky egg, I need 27*11+1 = 298 candy. I have 276 already, so I think the + should be 22.  See also #174

For further clarity.. I'm lacking 22, should this be `-22` instead of `+`, maybe in red text?

**Comment by YesThatAllen** [comment]
I've used `yarn` and `yarn package` on my Mac, and am having some problems in this branch.

Once I've opened the list of Pidgey, I can no longer sort them by IV, level, etc. I can only sort the master list. 

- EDIT:  I CAN sort within the pokemon list if the master list is sorted by "sprite"

This is all under Mac OS 10.12.3, built using `yarn 0.20.3` and `node 7.5.0` installed via homebrew.

**Comment by YesThatAllen** [comment]
Another idea I had:

In the case of having 1 Sentret, and 122 candies, I think it would be more useful to show the +3 next to the number of evolves.


<img width="855" alt="screenshot_2055" src="https://cloud.githubusercontent.com/assets/2879972/23098823/cd64ef5a-f61d-11e6-85cb-79adb56c4674.png">

**Comment by YesThatAllen** [comment]
What does +0 mean here? Should the value be hidden if `0`?


<img width="813" alt="screenshot_2056" src="https://cloud.githubusercontent.com/assets/2879972/23098839/216fbecc-f61e-11e6-8394-b2fe7bd2fb59.png">
