### ISSUE TITLE
Show pokemon skill

### ISSUE THREAD

**Issue by Superbil** [vinnymac/PokeNurse#104]
Could show skill on pokemon detail ? That will help on select which one need to transfer or not.

**Comment by mackhankins** [comment]
You mean the moves?

**Comment by mackhankins** [comment]
<img width="727" alt="screen shot 2016-08-15 at 9 10 18 pm" src="https://cloud.githubusercontent.com/assets/2184080/17685782/d465b8e0-632c-11e6-96dc-4063b6a038a6.png">

Moves are part of #66 and #102 if that's what you're talking about.

**Comment by Superbil** [comment]
Oh, that is. Thank you @mackhankins
