### ISSUE TITLE
[Inquiry] Is it possible we will get banned from using this app?

### ISSUE THREAD

**Issue by breinntaguilar** [vinnymac/PokeNurse#109]
I read somewhere in reddit that using 3rd party apps are illegal and is possible to get banned.
Can someone confirm this?
Thank you.

**Comment by vinnymac** [comment]
@breinntaguilar there will always be a risk of getting banned, as we aren't sure whether or not they can detect unusual usage. However, we use pogobuf for this client, this isn't a bot, and we are interfacing with pogo as the mobile apps would. We also have attempted to keep the requests as similar in timing to the apps as possible, so as to not raise suspicion.

TL;DR Nobody has ever been banned for using PokeNurse.

See #52 for more information

**Comment by breinntaguilar** [comment]
thank you so much for that very informative reply @vinnymac 
i appreciate it very much! :)
