### ISSUE TITLE
Eevee's detail page shows wrong evolution image

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#133]
The detail page shows a Bulbasaur instead of Vaporeon, Flareon and Jolteon.

![bug](https://cloud.githubusercontent.com/assets/11468889/17988265/6aaa6922-6b25-11e6-9b6c-56107b6160e8.PNG)

**Comment by vinnymac** [comment]
@iPaulis I find this hilarious. Good find!
