### ISSUE TITLE
nickname's can only be 12 characters long

### ISSUE THREAD

**Issue by WilliamAnthony** [vinnymac/PokeNurse#134]
After I changed the nickname, the console output:

[+] Pokemon 317512073583467345 nicknamed MyNickName

seems ok, but after I refresh and the console output:

[+] Retrieving player's Pokemons and Calculating Evolves

my pokemon nickname is reverted to previous.

**Comment by mackhankins** [comment]
I can't replicate this error.  I rename a pokemon and refresh it's fine.  I log out and log back in it's fine.  Could you try again after a fresh login?

**Comment by WilliamAnthony** [comment]
yes, I already tried logout, login, rename several times before I post this issue.
Is there any debug message that can be activated to trace the bug?

**Comment by mackhankins** [comment]
What OS?  Also under window-> toggle console option there are some tools.  Maybe there is an error under console.

**Comment by vinnymac** [comment]
@WilliamAnthony What version of PokeNurse are you using? What OS are you using? Did you build the app yourself? What kind of account do you have (Google/PTC)?

**Comment by WilliamAnthony** [comment]
Found out the problem.
I tried to rename with pogo app, it restricts the input to 12 max chars.
I can rename successfully with PokeNurse If I rename them with 12 chars or less.
I think it will more user friendly if PokeNurse restrict the input or raise any error if the operation fails.
Sorry to bother you all with silly question.

**Comment by vinnymac** [comment]
@WilliamAnthony no that is completely reasonable, I had no idea it was restricted to 12 characters. We can easily limit that for you! Thanks for confirming the issue!
