### ISSUE TITLE
(index):22999 Uncaught TypeError: Cannot read property 'pokemon' of undefined

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#136]
I just tried to transfer a large amount of Pokemons (135 selected, but only chose to transfer not favourites) after my mass evolve. The countdown appears, but nothing is transfered. I don't know if there is any log I can show you or something, let me know pls.

![transfer bug](https://cloud.githubusercontent.com/assets/11468889/18024369/852a56fc-6c08-11e6-88e0-075955cf2f0b.PNG)

**Comment by vinnymac** [comment]
@iPaulis please upgrade to the latest version, v1.4.0

We can't be sure if this bug is still around or not.

**Comment by iPaulis** [comment]
I was with v1.3.2, but I already transfered all those pokemon in smaller groups, so I wont be able to try to replicate this until my next mass evolve.

**Comment by vinnymac** [comment]
Yea this was an issue in an older version and should be fixed for sure in our next minor release of 1.5.
