### ISSUE TITLE
Outdated movesets in details page

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#137]
In a given pokemon's details page the moveset of the pokemon is marked with a greyer colour among the other moves. Well, I have no idea why this is and only happens with 2 of my pokemon, so it is very strange, but the thing is that the move is not marked so I don't know which is my pokemon's quick move.
This bug only happens with 2 of my gravelers, but my third graveler shows the moves correctly marked.
![quick bug](https://cloud.githubusercontent.com/assets/11468889/18024434/97fedb98-6c0a-11e6-8578-33cfd836d4dd.PNG)

I just don't understand this, it seems very random.

**Comment by vinnymac** [comment]
Can you confirm this bug still exists in v1.4.0? @Wrexial added that feature, maybe he has some input here. Otherwise I will look into it.

**Comment by iPaulis** [comment]
Update:
I've been looking and the same problem happens with one of my starmies, but in this case with the charged move not being marked. However, in this case I know why it is happening. Movesets for starmie were changed after the last update, so now it can have Psychic and before that was not an option. I can see my starmie has psychic ingame.
![charged bug](https://cloud.githubusercontent.com/assets/11468889/18024521/d98484e4-6c0c-11e6-8199-fc800153e749.PNG)

**Comment by iPaulis** [comment]
Update 2:
OK, the problem was the same with graveler, the old attack was mud shot (dmg 6), the new one is called mud slap (dmg 15).

**Comment by vinnymac** [comment]
We probably need the new protobuf GAME MASTER v3 as json. If anyone has it, that would be useful. We have the v1 and v2 ones in the repo already.

This is the latest data I can easily find
https://gist.github.com/noxwyll/8c821408b1d943c3e500d91d77266368/f264e42f2e83bbe845841717f74b276c9801ba7d

**Comment by iPaulis** [comment]
I can confirm this bug persists in v1.4.0, the screenshots remain the same, movesets are outdated.

**Comment by iPaulis** [comment]
More info about the topic and the list of affected pokemons, moves and their dps after the update: https://www.reddit.com/r/TheSilphRoad/comments/4yqdfv/infographic_summary_of_all_aug_19th_moveset/

**Comment by Rplus** [comment]
This issue might be closed with #170.

**Comment by vinnymac** [comment]
Nice! I have added it to the milestone.
