### ISSUE TITLE
Transfer bug in v1.4.0

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#138]
I selected 2 pokemon, clicked transfer without favourites. Progress bar appeared, but didnt progress, is stuck at 0%, Status is Idle, and if I click in transfer again it says an action is taking place, but nothing seems to be going on.
![transfer bug 2](https://cloud.githubusercontent.com/assets/11468889/18024847/e3e179f8-6c14-11e6-8054-2ffae98f6ea2.PNG)

Update: I restarted the program, followed the same steps and had no problem to transfer, so I couldn't reproduce the bug and I don't know why happened in the first place. Very nice progress bar btw.

**Comment by vinnymac** [comment]
I see some weird things happening if you double click the confirm transfer or evolve buttons. We might need to add running checks to them so that you can't accidentally add additional operations. I don't have any other guesses as to why this was happening for you, couldn't reproduce.

**Comment by iPaulis** [comment]
No no, the error message was intentionaly prompted by me clicking to transfer again, because before that it was not really doing anything, that was the real problem.
