### ISSUE TITLE
Add ability to sign out

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#140]
Currently the sessions last for 30 mins, which we might want to indicate in some way. But we also would like people to be able to sign out and be brought back to the sign in page if possible.

This might mean we need to create a new client instance to properly sign out.

We already have functionality for this on develop!

**Comment by weirdapps** [comment]
does this mean if I close poke nurse and then login into a bot or the official client, it will log two instances of the same account running and ban me?

**Comment by vinnymac** [comment]
You will not be banned for logging into two devices. People own multiple tablets as well as phones. Sessions last 30 mins if you were to sign in twice on your own phone using the pogo app nothing bad would happen. You would just create two separate sessions, and use one of them. So to answer your question, it will log into two instances, you won't be banned.

Pogobuf is the source of how this works. If you want to learn more look towards that library. It would be nicer if the session was renewed instead of repeatedly logging in, but that is how it currently works.

**Comment by weirdapps** [comment]
thanks a lot @vinnymac for the reply.
