### ISSUE TITLE
On OSX, closing the window leaves the application in the taskbar

### ISSUE THREAD

**Issue by asiansteev** [vinnymac/PokeNurse#141]
and there's no way to reopen the window without fully closing the application and reopening it.
Steps to reproduce:
1. open pokenurse
2. (optional) sign in
3. click the red x in the top left of the window to close the window

observe:
- clicking the pokenurse icon in the taskbar down nothing
- right clicking the icon and selecting 'show all windows' does nothing
- the only real option is to close the application and restart it

expected:
clicking the icon in the taskbar should reopen the window or clicking the red x should close the application

**Comment by vinnymac** [comment]
I think when you hit the x the close event in the main process for electron is getting fired. I will look into adding some custom logic for windows and os x to mitigate this for v1.5.0.
