### ISSUE TITLE
Alternative App Icon

### ISSUE THREAD

**Issue by hacknug** [vinnymac/PokeNurse#142]
Hey guys!

A little after I found out about PokeNurse I decided to design a new icon for the Mac app. I just thought that maybe someone would be interested in having it or even maybe on using it as the official one. I used the PokéCenter logo as a base for it. I also did a blue and a yellow version in case someone would want to use the version of their team.

If any of you want me to do a Windows version or want the .icns for the Mac, just let me know. Opening this issue just to show you what I have and to get some feedback from you guys.

![pokenurse](https://cloud.githubusercontent.com/assets/1107521/18203453/75e5d7e8-7117-11e6-9e0f-d19759bc1dc0.png)

**Comment by vinnymac** [comment]
@hacknug awesome new logo, you should do a PR and replace the ones we have in `imgs` with your new one 👍

**Comment by mackhankins** [comment]
Love it, awaiting pull request.  Thanks

**Comment by hacknug** [comment]
I just submitted the pull request with the new icons and their source files. Let me know if you need me to add or change anything. Btw, I've used the red icon as the default one to replace the ones the app was using. You'll find the other two colors inside the imgs folder.
