### ISSUE TITLE
MaxCP is wrong

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#146]
There seems to be a real problem with the MaxCP maths. The bug is not completely consistent, happened with some pokemon and not with others. MaxCP is not completely mistaken because it corresponds with the previous CP of the pokemon. I mean, my guess is that MaxCP seems to be showing MaxCP-1*PowerUp, so one step less than it should.

Examples:
![max cp](https://cloud.githubusercontent.com/assets/11468889/18220827/048ad03a-7176-11e6-81fa-55a0b4f1950b.PNG)
![max cp 2](https://cloud.githubusercontent.com/assets/11468889/18221124/a8fc6d1a-7179-11e6-9950-23d212c650bc.PNG)
![max cp 3](https://cloud.githubusercontent.com/assets/11468889/18221126/ac2693ee-7179-11e6-9d85-cc329aa475b5.PNG)
![max cp 4](https://cloud.githubusercontent.com/assets/11468889/18221128/af640a28-7179-11e6-9e34-3f10796e6ebc.PNG)

**Comment by iPaulis** [comment]
So now I found 2 cases where MaxCP was correct, exactly as real CP, so I dont know why it shows 1 power up less CP sometimes and correctly other times.
![max cp 5](https://cloud.githubusercontent.com/assets/11468889/18221417/487fcf00-717d-11e6-82b5-218a7eb4d9e4.PNG)
![max cp 6](https://cloud.githubusercontent.com/assets/11468889/18221419/4b99a6e8-717d-11e6-84f6-aaddf62e5b3d.PNG)

**Comment by vinnymac** [comment]
Sounds like an off by 1 issue. The protobuf files have changed, and I am certain some of our info is out of date, so maybe the max CPs were part of that. I know some of the max CP logic came from [blossoms java code](https://github.com/Wolfsblvt/BlossomsPokemonGoManager/blob/master/src/me/corriekay/pokegoutil/utils/pokemon/PokemonCpUtils.java), so maybe we can see if that has been updated to match the newer versions of pogo.

@mackhankins any ideas?

**Comment by Rplus** [comment]
The formula is correct.
And this issue due to the Level limitation is `trainer's level +2` in API,   
but it is `trainer's level +1.5` in APP interface.

ref:
http://www.pokemongochamp.com/bug-in-buddy-system-allows-to-power-up-pokemon-beyond-max-level/

**Comment by vinnymac** [comment]
I am not so certain that this should be fixed. I will reopen it if someone has a good argument. Reference:
https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/477
