### ISSUE TITLE
Do update check upon app starting

### ISSUE THREAD

**Issue by nevet** [vinnymac/PokeNurse#148]
I'm not sure if this has been implemented or not, but I just found I'm still using v1.1 😂

It would be nice if the app could prompt about update when the app restarts.

**Comment by vinnymac** [comment]
I've dealt with this in the past, there are some libraries for electron that can make it a little easier to do auto updates. An update check would be easier than that. For such a small project this is low priority and would be a good first PR for anyone who wants to get involved.

A good place to start with auto updates would be https://www.npmjs.com/package/electron-updater but that is a lot more complicated than checking.

With checking for an update I'd do something simple like compare the current apps package json on start to the package json on master branch. If they appear to be different, point the user to the latest release. Any failures to detect should probably just start the app as normal.
