### ISSUE TITLE
StopError: Status code 102 received from RPC

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#154]
This bug hapened while I was trying to unfavourite a pokemon. 
![unstar bug](https://cloud.githubusercontent.com/assets/11468889/18407333/ad2e563e-770d-11e6-93a4-1dd4decb979d.PNG)

**Comment by vinnymac** [comment]
This isn't a bug, it just means that your authenticated session has timed out. Sessions only last 30 mins. We plan on either finding a way to renew the session automatically, or informing the user that the session has timed out by logging them out.

This is especially dangerous when doing large transfers with a lucky egg thinking it is working.

**Comment by iPaulis** [comment]
Yeah, there is no way we can know that is the reason behind it if there isnt a warning. That's a problem, because the user expects the program to work normaly. Renewing the session automatically would be awesome, so we could use the program without having to worry about auth time out.
