### ISSUE TITLE
iOS user but Pokenurse registers as Android, concern?

### ISSUE THREAD

**Issue by mrrosso84** [vinnymac/PokeNurse#156]
I noticed after trying pokenurse that it registered as an Android device in my email account.  Would this raise concern for "suspicious activity" for iOS users?  Just curious is there's a way to have it appear as if I'm logging in from an iPhone instead?

**Comment by vinnymac** [comment]
No need to be concerned. You can obtain numerous phones IRL. However, this doesn't mean they won't ever detect suspicious activity through PokeNurse's request layer. We currently use pogobuf, and until people start getting banned for using pogobuf, you shouldn't be concerned.

The new updates have new layers of security, so Niantic might be beefing up against third parties. So who knows what is coming. If you are still truly worried about being banned. My recommendation would be to avoid third party software.

**Comment by mrrosso84** [comment]
Thanks for the response.  I appreciate the work on this thing.  Super helpful.
