### ISSUE TITLE
Put the buttons Transfer and Evolve on the header/navbar

### ISSUE THREAD

**Issue by lmcarreiro** [vinnymac/PokeNurse#157]
When I'm transferring my pokemons, if I'm on the bottom of the page, I need to scroll up to the top, click on transfer, then I need to scroll down again so I can move to the next pokemon on the list. I repeat this process of scrolling up, down, up, down a thousand times.

I know that I could sort by COUNT column, but I like to see the list in the order that evolved species appear next one to another. Some pokemons I keep a large count because I already have the candies to evolve all of them.

Anyway, it would be very helpful if the navigation bar has the buttons "Transfer" and "Evolve".

**Comment by lmcarreiro** [comment]
Bootstrap already have a fixed top nav bar:

http://getbootstrap.com/examples/navbar-fixed-top/

**Comment by lmcarreiro** [comment]
I try it out using console, It worked as I expected. I've just made tree changes:

1) Put the classes `navbar navbar-default navbar-fixed-top` on the `<header>` tag:
`<header class="header navbar navbar-default navbar-fixed-top" id="profile-header" ... >`

2) Put 150px of margin-top on the main container:
`<div class="container" style="margin-top: 150px;">`

3) Move the buttons after `<p id="username-h">...</p>` label:
```
<div class="col-xs-6"><p id="username-h">lmcarreiro</p>
<span class="pull-right">
    <input type="button" class="btn btn-warning" id="transfer-btn" value="Transfer selected">
    <input type="button" class="btn btn-danger" id="evolve-btn" value="Evolve selected">
</span>
```


I would make a pull request, but I never worked with Electron neither React, so I didn't.

**Comment by lmcarreiro** [comment]
I can make the pull request, if the owner agree with this idea. Or someone else could do it too, to see if it will merge.

**Comment by vinnymac** [comment]
Yeah @mackhankins and I have discussed this before. One thought I had was making them absolutely positioned in the lower right, like google does with a lot of actions. Not 100% sure about the best design here, but we could do it better for sure. A PR is definitely welcome for this.

**Comment by vlechemin** [comment]
And also the refresh button :)
I'm not sure if it's a bug but once I rename or now even star (this one was working for sure), I have to refresh to see the change :(
Thanks!
