### ISSUE TITLE
[Request] New Pokemon Go update shortens evolution animation time

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#162]
So now the evolution animation time is shorter and more evolutions can be done during the same lucky egg. Before the animatino time was about 25-30 secs, now it seems to be around 18-20 secs.
It would be great to update PokeNurse to match the new animation times more or less, so we can take advantage of this change.

**Comment by sudoash** [comment]
I've raised a pull request for this, https://github.com/vinnymac/PokeNurse/pull/163.

**Comment by vinnymac** [comment]
When I do a release next I will close this :)
