### ISSUE TITLE
New baseStats and new CP

### ISSUE THREAD

**Issue by Rplus** [vinnymac/PokeNurse#165]
Niantic Update Pokemon GO CP
http://pokemongo.nianticlabs.com/en/post/cp_update/

ref: gamepress' note
https://pokemongo.gamepress.gg/news/pokemon-go-cp-update

Pokemon's baseStats update ref:
https://www.gamefaqs.com/boards/180967-pokemon-go/74599677/866468322

**Comment by TheQL** [comment]
I appreciate your effort, but did I miss that this was ever adapted to a new API version? 0.45 will probably stop working very soon as well...

**Comment by vinnymac** [comment]
Yea this is currently why development has slowed to a halt. Niantic is playing the cat and mouse game and most of us don't have the time to keep up the good fight. I would love to work on this project more, but they keep making it more difficult every day.

**Comment by TheQL** [comment]
Yeah, this is really sad... I would have loved to use Pokenurse in the last few weeks though to plan my evolves or to be entirely sure about the IVs of my 'mons, but somehow I managed ;)
