### ISSUE TITLE
New Pokemon result in a white screen at launch

### ISSUE THREAD

**Issue by YesThatAllen** [vinnymac/PokeNurse#173]
Once ~a new Igglybuff~ a new Gen2 pokemon has been caught, PokeNurse opened to a white screen.

After it was evolved(or transferred), PokeNurse can open again.

**Comment by ModestZombie** [comment]
Same issue, that's good to know I can evolve it in the meantime

**Comment by jasonlo1000** [comment]
Having the same problem too after hatching a Smoochum.

**Comment by shaival141** [comment]
Me too having same problem, I've got elekid and pichu, 
and I don't want to evlove them

**Comment by chri5gilbert** [comment]
Same issue with Togepi

**Comment by 4tw0ne** [comment]
![2ndgenwhitescreen](https://cloud.githubusercontent.com/assets/23730476/21297725/5f55cbaa-c54a-11e6-827e-406d9a9acfce.PNG)
In case any coders need the error but do not have any 2nd gen yet

**Comment by vinnymac** [comment]
@4tw0ne thanks for the stacktrace, looks like the error is happening because we have no base stat data on these pokemon. I should be possible to fix the white screen issue by continuing if we fail to find any usable stats, but we will still have visual bugs, missing avatars/stats etc. I will see if I can put something together later today.

**Comment by vinnymac** [comment]
If you know how to build from the develop branch you can give the fix a try. Let me know how it goes.

**Comment by 4tw0ne** [comment]
Thank you, @vinnymac 
I have used Eclipse for java awhile back, and will see what I can do to try the dev-build. 
Bit rusty myself, any tips for new comers to get started would be highly appreciated. 
I can follow instructions well, but sometimes just need a bit of direction.

Other than that, I am happy to report any errors I can duplicate.

**Comment by nbyouri** [comment]
I ran the develop branch and and it's still a blank screen.

<img width="897" alt="screen shot 2016-12-20 at 13 48 58" src="https://cloud.githubusercontent.com/assets/2135560/21351073/16a8d236-c6bb-11e6-8b3e-767559164b9f.png">

**Comment by vinnymac** [comment]
@nbyouri thanks for getting it running, I can't even open the app on my phone anymore for some reason so I appreciate it. I just pushed another change that makes sure there are 802 slots for all pokemon up to Alola. The count error above was from it being unable to find a spot to count the new pokemon that are coming down from the API. If only I could get one of these new pokemon on my account I would be able to debug this very quickly.

**Comment by nbyouri** [comment]
I can confirm the app launches 👍 
Now it needs the sprites added! 


Thanks!

**Comment by vinnymac** [comment]
@nbyouri I added sprites (649), cries (721), and some non-3d images (721) since I can't find 3d ones. Let me know if they work 👍

**Comment by garykw** [comment]
@vinnymac Thanks for the update. First time running dev for this repo but I can confirm that the app is now displaying the list now along with the image of igglybuff.
