### ISSUE TITLE
Unable to log in to 2.0

### ISSUE THREAD

**Issue by adisor19** [vinnymac/PokeNurse#183]
"Error: No auth info provided"

I reset the App Password just in case but still keeps happening. I have no idea what to put as hash key.. so I left that empty.

I should mention that I was able to log in just fine in previous versions.

**Comment by hungsu** [comment]
Same issue here. Is there really no one else having this problem?

**Comment by tohmyp** [comment]
same here

**Comment by vinnymac** [comment]
If you can't login to `v2.0.0` please use `v1.9.0` for now. 

I am able to login successfully with a hash key and without a hash key on `v2.0.0`. It could be pogobuf or the way I implemented it. It would help a lot if you could tell me which authentication type (Google or PTC), whether or not you entered a hash key, and which OS version of the app you are using (Linux/macOS/Windows), thanks!

EDIT
After investigating this a bit, it seems like I am able to reproduce the issue only for Google logins. The login method is supposed to return a token, but the token is undefined. I will see if pogobuf knows anything else about it.

**Comment by Picosu** [comment]
Hello,
I encouter the same problem. With google account too, without hash key. 
And a quick question, what is the "hash key" you are talking about ? I may have missed something about that

**Comment by vinnymac** [comment]
@Picosu You can read about hash keys and what is going on [here](https://hashing.pogodev.org/).

I have confirmed with the pogobuf team that this is indeed a bug on their end. Please use v1.9.0 for now until they resolve this issue.
