### ISSUE TITLE
Unable to transfer any pokemons with 2.0.1

### ISSUE THREAD

**Issue by adisor19** [vinnymac/PokeNurse#184]
It just keep going and going and going... I waited over 20 min and nothing was transferred. Used to work fine in 1.9 and earlier.

**Comment by YesThatAllen** [comment]
Same problem here, started in 2.0.0

I'm using a Mac and can successfully login and list using PTC login (no hash keys)

**Comment by vinnymac** [comment]
Please specify OS version, method of login, and if you use a hash key. I can forward this info to Pogobuf and see what they think.

I will try to reproduce. Please use v1.9.0 in the meantime if you are having trouble.

EDIT
Yea I see this, it seems like no response comes back the promise is not resolved or rejected, weird.

**Comment by ghost** [comment]
Same issue here, Windows 10 x64 en Server 2012R2, Google login with a Hash Key

**Comment by Dog-Pack** [comment]
Windows 10l, V 2.1 no hash, google log in no transfers but will rename them.

**Comment by vinnymac** [comment]
@adisor19 @YesThatAllen @Dog-Pack @baulie I have verified the issue with pogobuf and they have come up with a fix. Once they release the fix (later today) I will release `v2.0.2` of PokeNurse.
