### ISSUE TITLE
Cannot transfer and evolve with RPC 100

### ISSUE THREAD

**Issue by 4tw0ne** [vinnymac/PokeNurse#187]
When attempting to mass transfer any amount of 2 or more, an RPC error 100 is received. Looks to be some pogobuf updates which may help. 

Single transfer do work, along with renaming and favoriting.

**Comment by YesThatAllen** [comment]
Same issue for trying to evolve >1 item at a time


Perhaps a solution is in https://github.com/cyraxx/pogobuf/issues/123

**Comment by shaival141** [comment]
Similar issue, I guess Niantic's got big changes in the GM, and there's a client update to come.

**Comment by scuellar** [comment]
Same problem here. It's definitely a server side change... I would love to know if it gets fixed!

**Comment by vinnymac** [comment]
😢  Hopefully this isn't as bad as it sounds. I have been very busy lately and haven't been able to update the dependencies, hopefully we can work things out. If pogobuf keeps things up to date I should be able to add support for the latest and get a new version in your hands. Thanks for letting me know.

**Comment by Dog-Pack** [comment]
![pokenurse](https://cloud.githubusercontent.com/assets/24977516/23030285/355c829a-f465-11e6-8d09-0ad588c1351e.jpg)
Same for me :(

**Comment by YesThatAllen** [comment]
To get notifications on this problem, there is a "Subscribe" button.

For everyone who is subscribed, Me Too posts without new information don't help much.  Adding reactions to comments which are already posted is a great way to show Vinny support in getting this addressed.

(yes, I'm fully aware this post doesn't add much, but I don't want to have to unsubscribe from this known-issue)

**Comment by Dog-Pack** [comment]
I am sorry are you having ago at me for posting?

**Comment by mtran66** [comment]
maybe develop a workaround for now to do singular transfers and evolves?  since you can still do it 1 at a time.

**Comment by bryce35** [comment]
any updates of when the new version will be released??? This is some of the best piece of software i've ever come across and I hope there is a new update very soon.

**Comment by JokerLion** [comment]
It's getting worse - can't log in.  Received this error:
"Error: operation timed out after 4581 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100"

**Comment by Redarion** [comment]
Hi guys, totally new to the project: I was searching for something like this for month, then I found you and here I get error even before using it!
same error as @JokerLion 

> "Error: operation timed out after 4581 ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100"

**Comment by vinnymac** [comment]
Thanks for all the interest everyone. It looks like `pogobuf` (the tool we use to interact with the pogo API) does not yet support the latest updates from Niantic. Updating the dependencies didn't help, but it looks like some devs are working on the issue. If we do get a fix it may mean support for only `0.51` API and above. Which will require a token (it would cost $) and maybe even CAPTCHA.

**Comment by Redarion** [comment]
So if I get those [3 -370€ token](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer) to get the hash should  it should works properly?

**Comment by scuellar** [comment]
You might be aware, but just in case: nicoschmitt claims this version of pogobuf is up to date:
https://github.com/pogosandbox/pogobuf

**Comment by ghost** [comment]
I'm in the same boat and can no longer log in anymore before the "5 tries with error: Fetching RPC endpoint failed, received status code 100" error message.  I visited the above PogoBuf page but I cannot find any sort of GUI to download, just code.  Is this in project mode at this time?  Unfortunately, I cannot be of help, but happy to scour for bugs once in BETA -Colleen

**Comment by Redarion** [comment]
Don't know if it may help, but [this project](https://www.google.it/amp/s/amp.reddit.com/r/pokemongodev/comments/4vq84x/blossoms_pokemon_go_manager_xpost_rpokemongoiv/) use a workaround with a token. I'm not a programmer but maybe you can find it usefull

**Comment by vinnymac** [comment]
A new release with the latest changes from develop will be out later today.

**Comment by YesThatAllen** [comment]
This is a fantastic improvement, thanks so much!

interestingly, the original problem: can't transfer more than one pokemon at a time is still present. :sob: 

At least we can still figure out what should get transferred now.

**Comment by 4tw0ne** [comment]
I am still having this too, which is why I opened this ticket in the first place. 
Should this be re-opened or re-submitted?

While transfers not working is minimal, the evolution ability on the other hand would be great to have once again. Batch evolves may not be possible with the new api [just a guess], but the old timer method would even be better than nothing at all. 

Manually Mass-evolving is a tedious experience to say the least.

**Comment by vinnymac** [comment]
Reverting the code to how it used to work is going to take quite a bit of work. I am not sure how much time I have right now to make that happen. If someone else wants they can go back to the older versions and stitch it back to life. In the meantime I will probably get any low hanging fruit out of the way. It is frustrating that the main feature of the app is broken.

Most of the logic that we reverted can be found in trainer.js in [this diff](https://github.com/vinnymac/PokeNurse/compare/v1.6.2...v1.7.0). If someone wanted to look into it. Other than that, probably some status/progress related changes would need to be reverted.

**Comment by Redarion** [comment]
again RCP 100 on log in from today.
Don't Know if they made some new change or what, but that's a clear warning that Niantic don't want third party app to work....

**Comment by ghost** [comment]
It's a forced API update:

> "Niantic forced the API to version 0.57.4 and changed the login sequence so accounts will not log in currently.
> If your scanners are still connected then it's your choice whether to run the risk of continuing to scan and possibly get them flagged or to log out and wait.
> If your scanners are not connected then close the app or uncheck them all so that they stop trying to log in.
> Avoid using it at all on the same IP as your main account right now, people are getting in game messages about modified software detected."

**Comment by Redarion** [comment]
Actually I don't want to use any scan: I choose Pokenurse because it's just a tool to manage all my pokemon and rename them based on their name for practical use. 
I think that should be the only reason someone should use a third party tool.

**Comment by ghost** [comment]
Yes but Niantic clearly doesn't want ANY 3rd party tool to be used...

**Comment by Redarion** [comment]
we can go on talking about what should or should not be done, but the question is: should we pay for getting an "official" hash (and go back to the pay to get more as always) and don't have any problem or should we wait for an update?

**Comment by hacknug** [comment]
The app is working without any issues other than the ones we already knew of (running dev branch, with a hash key with version 5704 of the API).

**Comment by hacknug** [comment]
I think we should be able to solve batch transfering by passing an array with the mons id to this method: https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pok%C3%A9mon-Go-API-Methods#releasepokemonpokemonids--promise

**Comment by hacknug** [comment]
Sorry for the semi-spammy comments but I wanted to let you know I have batch transfers _working_.

The problem with my fix is that I don't think it's using the real multi-transfer method the game uses to transfer them all at the same time but transfering them one by one without any delays. I've tried passing an array with the selected id's but for some reason it wouldn't work (I'm not that good when it comes to real dev haha). Keep in mind that if you try to transfer your buddy mon, the app will log it as a successful transfer but it'll still be there.

Here's a link to a branch in my fork so you can test the feature if you feel like it. Remember that you'll need a hash key and use version 5704 of the API in order to log in.

https://github.com/hacknug/PokeNurse/tree/fix-batchtransfer

**Comment by vinnymac** [comment]
@hacknug yea this is similar to what we used to do. Except we were using a delay method to artificially recreate the delay for a POGO client based on our best guess. We also had UI for indicating how long it would take in total based on the length of the delay. I think for now this should work for both evolves and transfers, but we should probably add a kind of delay even if in the meantime it isn't displayed to the user. 

Alternatively we could just display each transfer one at a time, and a count of all the transfers. If you make it a PR we can move the discussion for this over their and I'll be around all weekend to help out.

Also for those who are getting RPC 100, get a hash token and login to the latest version of the app (v2.2.0) using the 5704 API. This should allow you to start using the app successfully again.

**Comment by hacknug** [comment]
@vinnymac the thing is we don't need to wait between transfers anymore because the game implemented its own batch-transfering method (not for evolves though). According to `pogobuf` the only thing we need to do to use this *new* method is to pass an array with the selected mons id's instead of passing them one by one.

**Comment by vinnymac** [comment]
@hacknug 👍 we can discuss in PR.

For everyone else who is having issues with their google account it seems to be a general issue with most third party apps right now. We aren't the [only](https://github.com/Phaetec/pogo-cruncher/issues/95) [ones](https://github.com/pogodevorg/pgoapi/issues/189) having issues. Which means this will happen to all versions of PokeNurse until one of our dependencies fixes it.

**Comment by jjaeyy** [comment]
Im using PTC for login. I've had this error since the previous version. 
From what i'm reading this is an API problem?
Is there anyway around it?
Thanks

![llll](https://cloud.githubusercontent.com/assets/26343211/23824919/06a400b4-06bb-11e7-82b1-155e2ac9fb75.png)

**Comment by vinnymac** [comment]
I have now moved the discussion for failed logins to #211.

This can now be strictly for transfer/evolve issues.
