### ISSUE TITLE
Please upload AppImage

### ISSUE THREAD

**Issue by probonopd** [vinnymac/PokeNurse#188]
Providing an [AppImage](http://appimage.org/) would have, among others, these advantages:
- Works for most Linux distributions (including Ubuntu, Fedora, openSUSE, CentOS, elementaryOS, Linux Mint, and others)
- One app = one file = super simple for users: just download one AppImage file, [make it executable](http://discourse.appimage.org/t/how-to-make-an-appimage-executable/80), and run
- No unpacking or installation necessary
- No root needed
- No system libraries changed
- Just one format for all major distributions
- Works out of the box, no installation of runtimes needed
- Optional desktop integration with `appimaged`
- Optional binary delta updates, e.g., for continuous builds (only download the binary diff) using AppImageUpdate
- Can optionally GPG2-sign your AppImages (inside the file)

`electron-builder` has support for generating AppImage files out-of-the box; in fact, it's the default for Linux.

[Here is an overview](https://github.com/probonopd/AppImageKit/wiki/AppImages) of projects that are already distributing upstream-provided, official AppImages.

**Comment by vinnymac** [comment]
Sure

**Comment by vinnymac** [comment]
Here are AppImage links for the latest release. I will start releasing them from now on.

[AppImage ia32](https://github.com/vinnymac/PokeNurse/releases/download/v2.1.0/PokeNurse-ia32.AppImage)
[AppImage x64](https://github.com/vinnymac/PokeNurse/releases/download/v2.1.0/PokeNurse-x64.AppImage)

**Comment by probonopd** [comment]
Thanks. Launches well on Ubuntu 16.04.

Added to https://github.com/probonopd/AppImageKit/wiki/AppImages
