### ISSUE TITLE
error: "unsupported version for hashserver:5300/1.23.0"

### ISSUE THREAD

**Issue by surrepticious** [vinnymac/PokeNurse#194]
I get an "unsupported version for hashserver:5300/1.23.0" error as of yesterday using v2.1.0

I'm using the same pogobuf hashkey as I was with v2.0.3 a few days ago and everything worked fine then. Seems the move to 0.53 API is causing it.

**Comment by vinnymac** [comment]
I may need to bump us up to 5702 or maybe let it be user defined so users can try various API versions.
