### ISSUE TITLE
Github download: network fails

### ISSUE THREAD

**Issue by alanpcs** [vinnymac/PokeNurse#200]
It is not an issue of the project itself, but every time I try to download a new release, the download stops after some point. I need to try downloading it at least 5 times :cry:  

http://prntscr.com/eggwyc

Would it be possible to host the releases alternatively on another host?

P.S.: This tool is awesome! Great work :+1:

**Comment by hacknug** [comment]
Are you still having issues downloading the app from GitHub? I can reupload to some other host but I think the best would be to find out why it is that you can't so we can solve your issue and keep everything in it's right place (this repo).

**Comment by YesThatAllen** [comment]
I've had no issues downloading from github. The full releases end up coming from s3, I'm not sure there's a better way to go here.

**Comment by garette1** [comment]
i cant download too

**Comment by garette1** [comment]
i cant download too

**Comment by vinnymac** [comment]
@garette1 @DemonKart can you download other things from other repositories?

Try these files they are smaller
https://github.com/sass/node-sass/releases

If it downloads successfully I would say it is likely a network and connectivity issue. If it doesn't then you are probably blocking github or github is blocking you for some reason (which I doubt).

**Comment by alanpcs** [comment]
Sorry for taking this long to answer again.

After 12 tries, it downloaded until the end. Maybe it is instability in the network. Probably Github deny connections that oscillates too much or if the download speed gets too low.

Thanks for the responde anyway!
