### ISSUE TITLE
Error while transferring

### ISSUE THREAD

**Issue by ghost** [vinnymac/PokeNurse#201]
I get the following error when transferring more than 1 Pokémon at the time.

Anyone?

![image](https://cloud.githubusercontent.com/assets/16636556/23658946/b6e80ada-0344-11e7-95ce-4023d443fdeb.png)

**Comment by Redarion** [comment]
this is a common problem as in #187 
I think they are working at it

**Comment by ghost** [comment]
Aha! Thanks! Missed that one.
