### ISSUE TITLE
[Question] Will the hash key solve the login issue?

### ISSUE THREAD

**Issue by Redarion** [vinnymac/PokeNurse#203]
As by title, will it solve the login problem or is it useless at the state of the art?

**Comment by hacknug** [comment]
I don't know what issue you're refering to but I can log in without any issues using version 5704 of Bossland's API on the development branch.

**Comment by hacknug** [comment]
Tried to log in earlier without a hash key and got an error (I guess the one you experienced). So to answer your question, it will.

**Comment by Redarion** [comment]
So you highly recomand to buy it one? Is it from [here](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer)?

**Comment by mhastrich** [comment]
If the comment from lennert1984 in Issue [#205](https://github.com/vinnymac/PokeNurse/issues/205) is right it won't help to use Hash Key:

> Same issue here.
> With or without Hash Key, with or without 2 step verification.

**Comment by ghost** [comment]
Correct.
It is not a solution for me at this moment.

Keep getting: 
> Error: operation timed out after x ms, 5 tries with error: Fetching RPC endpoint failed, received status code 100

**Comment by hacknug** [comment]
I don't wanna recommend anything in case it end ups not working for you. The only thing I can say is that PokéNurse was working with both PTC accounts I tried when using a hash key and version 5704 of the API on the develop branch (after updating dependancies with `npm install` and `yarn`).

What I would NOT recommend is using any third party app without a hash key, even less now that Niantic is sending this notices. This doesn't mean that you need to buy one, you can use one of the free shared ones Incacode posts online.

**Comment by mhastrich** [comment]
Can anyone explain how this works or post a Link to a tutorial?
Couldn't find much information about it :(
I used it without hash before, perhaps i should change.

Login with Google Account isn't working for some days now unfortunately i don't have a PTC account.
Perhaps PTC is working and Google not?

**Comment by hacknug** [comment]
I don't think it will work without a hash key. No tutorial that will solve this is Niantic's forcing everything to connect through the latest version of the API (5704). Don't expect it to work if you don't have a hash key unless you read that Niantic is allowing users to use the OLD/free API.

If you're trying to log in with a hash key and still can't get in, let me know.

**Comment by Redarion** [comment]
I just bought an HAsh Key but can't log in

**Comment by hacknug** [comment]
Good. At least now we have something to work on. Are you song the last version of the app? Vinny released a new one last night.

**Comment by Redarion** [comment]
yep with also the possibility to choose the API version. But the question is: was [this ](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer) the right website??

**Comment by ghost** [comment]
As discussed on Discord, I keep getting this error with the latest version installed:

![image](https://cloud.githubusercontent.com/assets/16636556/23799467/f51093f2-05a8-11e7-9659-2ed689a720d3.png)

**Comment by vinnymac** [comment]
Yea [this](https://talk.pogodev.org/d/51-api-hashing-service-by-pokefarmer) is the right site.

For questions and inquiries please use https://discord.gg/sSXCruy.
