### ISSUE TITLE
[Question/Feature Request] Warn on API changes?

### ISSUE THREAD

**Issue by scuellar** [vinnymac/PokeNurse#204]
I'll start with the question and follow up with the feature request.

Since the last forced update, many users have been flagged for using desktop managers (e.g. [BPGM](https://github.com/Wolfsblvt/BlossomsPokemonGoManager/issues/577) ) . I assume it is for not using the most recent API. 

It doesn't seem like PokeNurse has updated since the API force update. Is there any report of flag, warnings or bans? Or do you use a different method? I know in the end using a desktop manager is running a risk, but my questions are more specific to this recent update.

The Feature request: POGO blocks when a force update is pushed, forcing players to update. Presumably, you can detect the forced update and warn the PokeNurse user of a possible API change. This way we will avoid being banned just for an API mismatch.

**Comment by vinnymac** [comment]
I would expect something like this not to have to be done by PokeNurse. I would imagine this is something `pogobuf` should be responsible for during authentication. It is obviously a nice to have to prevent anything bad from happening to users, but I would imagine this type of thing being solved by every third party app is a big waste of dev effort.

**Comment by scuellar** [comment]
Thank you for your quick response.
