### ISSUE TITLE
store hash key across launches

### ISSUE THREAD

**Issue by YesThatAllen** [vinnymac/PokeNurse#216]
It's nice that the hash key is visible (not obscured as if it were a password)

It would be nice if I didn't have to re-enter the key on every launch. Could we get that saved as the username is?

<img width="765" alt="screenshot_2135" src="https://cloud.githubusercontent.com/assets/2879972/24074492/d6a82da0-0bd7-11e7-8cf3-230f9c07460c.png">

Perhaps as a part of #213

**Comment by vinnymac** [comment]
The two issues should be kept separate. This sounds like it may just be a bug since we are likely storing it in the json already.

**Comment by hacknug** [comment]
I fixed it on #213. We were storing the info but not retrieving it after launching the app.
