### ISSUE TITLE
Remove evolve and transfer

### ISSUE THREAD

**Issue by bebar69** [vinnymac/PokeNurse#22]
Can you remove Evolve and transfer just for make a reader app, Legit user can use it

**Comment by draggehn** [comment]
You can do that yourself if you want. duhminick is doing what he wants because it's his project. His purpose was not to make a "reader" app.

**Comment by vinnymac** [comment]
@bebar69 better yet, do a pull request to make it configurable?

**Comment by duhminick** [comment]
You don't have to use evolve and transfer...
