### ISSUE TITLE
Hastag Key Required?

### ISSUE THREAD

**Issue by SuziQ187** [vinnymac/PokeNurse#222]
##  Here is what I would like to see new or change within PokeNurse
I have used PokeNurse a couple times and LOVE it!! Been trying to sign in and get an error:
![image](https://cloud.githubusercontent.com/assets/26718343/24364461/7193a482-12d8-11e7-8bc9-22f3105b1340.png)

What does this mean?

I've never had this in the past and keep getting it when trying to log on.
Any help please?

## This is my environment

 - OS and Version: Windows 10
 - Version of PokeNurse - latest version downloaded V2.3.0

**Comment by Redarion** [comment]
As already said in other issue, because of third party library we use is now impossible to log in without an hash key.
You must have one to login almost with any unofficial third party app

**Comment by SuziQ187** [comment]
Thank you for your swift response.


How do I get  the hash key?


Regards,
Maria


________________________________

**Comment by Redarion** [comment]
I'm on mobile, but it should be said at least in one of my comment on issue #211 .
Take a look
