### ISSUE TITLE
Problem With login.

### ISSUE THREAD

**Issue by pampacuuz** [vinnymac/PokeNurse#224]
## This is my environment 

I have purchase the Pokehash Key but i cant login. 

![captura](https://cloud.githubusercontent.com/assets/27165506/24841233/a5aeb0ea-1d55-11e7-8587-899554b0566d.JPG)

 - OS and Version: Windows 10
 - Version of PokeNurse v2.3.0

**Comment by YesThatAllen** [comment]
This will happen in between the time when Niantic updates their API, and the library on which PokeNurse relies ( https://github.com/cyraxx/pogobuf/ ) is updated.

sit tight & maybe watch https://github.com/vinnymac/PokeNurse/issues/211#issuecomment-292744316

**Comment by pampacuuz** [comment]
So i need to wait pokenurse be updated?

**Comment by hacknug** [comment]
Exactly.

**Comment by pampacuuz** [comment]
PPL, Only i need to visualize the IV, does any version work at least to see that information?

**Comment by Redarion** [comment]
not for now: we are working on the upgrading of the third party api.
as soon as we have a working one we'll release it
