### ISSUE TITLE
incorrect monster name on candies

### ISSUE THREAD

**Issue by YesThatAllen** [vinnymac/PokeNurse#225]
##  Here is what I would like to see new or change within PokeNurse

This is an issue on the current develop branch.

I am seeing the wrong candy name on the modal

When I have a Pidgeotto's information modal open, it says `XX Pidgeotto` candy, not `XX Pidgey` candy as I would expect.

(It's the same for all mons) 

## This is my environment

 - OS and Version: macOS 10.12.4
 - Version of PokeNurse 2.3.0 (develop branch, even before the last commit by @hacknug )

**Comment by hacknug** [comment]
I'll try to take a look at it today to see if we can ship a fix this week with the dependancies update.

**Comment by YesThatAllen** [comment]
confirmed fixed in https://github.com/vinnymac/PokeNurse/issues/226
