### ISSUE TITLE
Refer to species instead of pokemon

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#25]
We have now created this relation `pokemons.pokemon[0].pokemon[0]` Where the first `pokemon[0]` refers to the species of Bulbasaur and helpful stats such as number of candies and the second refers to an instance of the pokemon Bulbasaur where we might have an attack offset.

We should rename this to something like `pokemons.species[0].pokemon[0]`. Maybe even better `monsters.species[0].pokemon[0]`

Thoughts?

**Comment by mackhankins** [comment]
`monsters.species[0].pokemon[0]` 👍
