### ISSUE TITLE
Values with HTML should have special names

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#26]
So that we don't collide with keys we should instead of `favorited` or `nicknamed` use names like `td_favorite`.

Is anyone else familiar with React? I feel we could use that to our advantage a lot here. Seeing all this string concatenation makes me sick, but I don't want to move to a large framework unless others are on board with the idea.

**Comment by mackhankins** [comment]
I think something like React would be better documented.  Frankly, doing research on electron has been like pulling teeth for me.
