### ISSUE TITLE
add level up selected

### ISSUE THREAD

**Issue by whiteshark-1975** [vinnymac/PokeNurse#27]

**Comment by mackhankins** [comment]
I think power up should be a single instance button on the row.  I don't think you would do that for multiples, well I wouldn't.  Rename could also be done like this if we ever have that feature.  We could call the column 'actions' or something.

**Comment by adamlieb** [comment]
+1 I'd love to be able to "power up" through the app. Very time consuming to do this manually. Similarly, would be great to see the "cost" to MAX CP in terms of dust+candies.

**Comment by vinnymac** [comment]
I think we have some of the Max CP formula down, not sure on how accurate it is, but it should be able to be used with the cpPerUpgrade data on being able to calculate the information that @adamlieb is requesting.

I agree with @mackhankins about this being a button on the subDataTable rows.

**Comment by vinnymac** [comment]
I just merged in power up, but it is still missing the max cost. We should be able to calculate max cp just fine, but I haven't figured out how to add up the total stardust and candy costs yet. We will probably add this to the tooltip once we figure it out.
