### ISSUE TITLE
Show all species in table, even when count is 0

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#28]
@mackhankins what do you think about showing all of them, and then we gray out the row and remove the expand button? It might be nice to see what people are missing as they scroll. Just an idea, I could see the argument against it because of wasted space, but it is only 151.

**Comment by mackhankins** [comment]
I think after the arrays have been refactored it would be pretty simple to implement.  I like it.  Could we get some labels on these issues?

**Comment by vinnymac** [comment]
I added some helpful labels and milestones. I think this can wait till later, but is a nice to have.
