### ISSUE TITLE
Refresh after transfer or evolve

### ISSUE THREAD

**Issue by mackhankins** [vinnymac/PokeNurse#29]
I think the list should refresh after evolve or transfer so you have fresh data to work with.  It could even be a dialog option.

**Comment by vinnymac** [comment]
@mackhankins we could solve this by refreshing after transfer or evolve, but is there a response we receive after transfer or evolve? That way we could just populate the UI with the new data instead of refreshing the whole thing. If this isn't possible, or is very difficult refreshing is fine with me.

**Comment by mackhankins** [comment]
I could be wrong, but I don't think there is a return event.  You might could drop the row from the data table which I'll check into.

**Comment by vinnymac** [comment]
Looks like the `pogobuf.Client` methods return `Promises` for chaining.
https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.client.js#L752

I guess we could do something like `client.releasePokemon(id).then` which I think we do elsewhere in main, like for `get-player-info`. Then all we have to do is a check, if the transfer was successful we can remove that one from the table. We may be able to just use a jQuery selector and do something like `$().remove()` on that part of the DOM. Not sure if `DataTable` would be happy, but we could just update the `monsters` object to remove it there as well.

Look at the branch `fix/transfer` where I started work on a kind of fix for this.

**Comment by mackhankins** [comment]
I know you can remove a row from the table and redraw it, but the complicated part is the sub-tables & sub-table id.  https://datatables.net/reference/api/row().remove()

That's why I thought it would be easier to refresh the 'monsters' data / table.

**Comment by vinnymac** [comment]
My changes aren't exactly what we want here. We should probably be refreshing after all of the selected pokemon have been transferred/evolved.
