### ISSUE TITLE
Favorite update doesn't persist collapse/expand

### ISSUE THREAD

**Issue by mackhankins** [vinnymac/PokeNurse#32]
So if I update a favorite via click, then collapse the child it will persist when I expand again.  I have to refresh the list to see that it actually updated. (or look in console)

My thoughts are:
1.  Hard refresh the list with `refreshPokemonList ()` in `ipcMain.on('favorite-pokemon')`
2. Store it in some type of local storage and clear that storage on refresh for that key.  Something like https://github.com/nbubna/store unless someone else has another library in mind.

Thoughts?

**Comment by vinnymac** [comment]
It looks to me like we are telling the server to change the favorite status and updating the UI without updating the state. Which is the wrong way to the think about it in my opinion.

Ideally we should be managing the local state and the UI should be responding to those changes.
Storing the state in local storage is fine (we could even write to disk using the `fs` module). Although that would fix the issue, it would require us to re-render the entire list.
1. User clicks Favorite UI which is in state `false`
2. Update local Favorite State to `true` and Render Favorite UI change
3. Send Request
   - Success
     - Update local Favorite State `true` and Render Favorite UI change
   - Error
     - Update local Favorite State `false` and Render Favorite UI change

In this scenario our state is our pokemon monsters object. If we switched to React this scenario would be a lot simpler for me to wrap my head around. Let me think on it some more. Do you agree with my thoughts above? Do you see an error in the logic?

**Comment by mackhankins** [comment]
You're on the money.  I just haven't written a lot of JS period so it's all new to me..  I'm onboard with React, but you're obviously going to have to get us started down that road.

Prioritize bugs and not take on new features if we're going to go towards React.

**Comment by vinnymac** [comment]
I say let's try to get everything out the door for Release v1.1.0 and then maybe we can do a better job with all of this. If we can patch/hug this issue for now, I will be happy with it. I would be glad to do a react milestone after this, and the codebase will become a lot more flexible at that point.

**Comment by vinnymac** [comment]
@mackhankins I tested my fix, and am curious what you think of it. Since you reproduced the issue, I'd like confirmation that it actually fixes it :P

**Comment by mackhankins** [comment]
Good job.  Tested and working.
