### ISSUE TITLE
How to calculate CP Per Upgrade?

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#33]
Just leaving this as a note. We need to figure out how to calculate CP Per Upgrade before v1.1.0. Other than that I think all other information for the modal is ready.

**Comment by vinnymac** [comment]
Instead of calculating it, I just used this data for now https://docs.google.com/spreadsheets/d/1xZ1daunztOgvOZxO7ABfJPF41-2mqMDzY1Qs_0OWwq8/edit#gid=399231321

**Comment by mackhankins** [comment]
I've seen this calc on a repo before, but I can't find it now...  On a different not check out https://github.com/Blossomforth/BlossomsPokemonGoManager/releases

**Comment by mackhankins** [comment]
I like how he had done move sets.
