### ISSUE TITLE
Use ♂ and ♀ in Nidoran naming

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#35]
Currently we display Male and Female which is not the norm.

**Comment by dr-ishmael** [comment]
I noticed that when I've renamed a nidoran by just appending something, like Nidoran♂_84, it displays the symbol correctly. Seems like this only affects the default name.

**Comment by vinnymac** [comment]
Yea the bug is not that we can't render the symbols. Just that the names do not currently have the symbols in them, we need to detect and replace the current names. I haven't rushed to do this one myself, it should be an easy first bug for someone who wants to get involved.

**Comment by dr-ishmael** [comment]
Cool, that's what I thought. Just wanted to help!
