### ISSUE TITLE
Sorting for CP does not work

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#37]
It looks like clicking on the sort icon to switch between ascending and descending doesn't sort CP.

**Comment by mackhankins** [comment]
I knew I forgot to test something.  That last PR had a default order change.  Needed sleep...

**Comment by mackhankins** [comment]
@vinnymac I can't replicate this issue.  Did you fix it?

**Comment by vinnymac** [comment]
@mackhankins I pulled the latest changes and tried this, this is supposed to change the sort order right?

![CP Bug](https://i.gyazo.com/8685a9809ccac98f36f787eff6bf3460.gif)

**Comment by mackhankins** [comment]
DT does sort strangely that the sort is far-right of the column.  It's the only script I've ever seen do it that way.

**Comment by mackhankins** [comment]
https://stackoverflow.com/questions/28575810/jquery-datatables-left-align-sort-icon

**Comment by mackhankins** [comment]
Hmm.. I'm gonna play with this.  That looks like nickname isn't sorting.

**Comment by vinnymac** [comment]
Oh! I didn't realize the sorts were like that. I thought it was the one behind it. You are right. And all the nicknames are the same here so it is working correctly I think?

**Comment by mackhankins** [comment]
@vinnymac ah, this is stuff with the same nickname isn't sorting.  Okay, that's a bug.  Good find.  Also, I'm going to move sorting to the far left of the column to see how it looks and maybe remove the favorites sort.  I'll try both.
