### ISSUE TITLE
Tooling

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#39]
So I would like to start using React if possible for this project. If anyone has any reason that we shouldn't I'd like to discuss it here. I am thinking of also using `babel` so we can include `react` as described [here](https://github.com/electron/electron/issues/1611). We would probably go the route of `require('babel/register')` to begin using JSX, so that we don't have to rely on any complicated configurations right now. Keeping it simple and clean.

As for data management using `redux` would be nice. But I think we don't need to make that decision right now, and it can wait till after we've added some react components to the project.

The order will probably be the path of least resistance, so something like this
- [x] Modal Detail
- [x] Login Screen
- [x] jQuery.DataTable Replacement

**Comment by mackhankins** [comment]
I'd like to hear what @duhminick thinks since it's his repo, but I'm for it.  It'll be a learning curve for me, but I've been meaning to dig into it.

**Comment by duhminick** [comment]
@mackhankins I'm all for it.  I've been meaning to learn React for a while now.

It would be rude of me to say that this project is mine since it's the two of you who have been doing the most, so if you two agree on something then by all means go for it.

Also I apologize for not contributing lately.  I'm preparing to go to school soon.

**Comment by mackhankins** [comment]
@duhminick It's a really cool idea with tons of potential.  I think our main goal is to find something that's scalable with project goals.  No worries about the school stuff though.  Real life happens sometimes 👍 

I'm personally very pleased with the UI functionality and as long as we can maintain that I'm a go.

**Comment by vinnymac** [comment]
Everything has been migrated to react except for the table which is still using jQuery.DataTable to draw all of our data. I am thinking of merging in my changes to master if you guys consider the changes on the `react` branch solid. We could then tackle the data table separately.

We also have React Dev Tools setup which should make debugging a lot easier.

Some alternative DataTables for react:
https://facebook.github.io/fixed-data-table/
https://react.rocks/tag/DataTable

**Comment by vinnymac** [comment]
@mackhankins found this one
https://allenfang.github.io/react-bootstrap-table/example

For now I merged in my react branch, which I am excited to see others build upon. @mackhankins and I decided to work on the table as a separate issue, as it is a lot more complex, and we will be removing jQuery.DataTables from the project with our own solution.
