### ISSUE TITLE
Cant log in with gmail acct

### ISSUE THREAD

**Issue by AbeSchmidtMoz** [vinnymac/PokeNurse#40]
I have 2 factor auth on my acct but cant turn that off- is that causing the login issue? I click Login with my gmail acct and password entered and nothing happens. I tried another Poke Trainer acct and that worked. Any help would be awesome!

**Comment by mackhankins** [comment]
Any messages in the console?

**Comment by AbeSchmidtMoz** [comment]
Not that im noticing, dont see anything pop up

**Comment by mackhankins** [comment]
Okay, I'm on the road, but we'll try to replicate.  I imagine there is a token involved for two factor.

**Comment by AbeSchmidtMoz** [comment]
Thanks for looking at this for me!

**Comment by mackhankins** [comment]
I'm making some notes for when I'm stationary 

> An App password is a 16-digit passcode that gives an app or device permission to access your Google Account. If you use 2-Step-Verification and are seeing a “password incorrect” error when trying to access your Google Account, an App password may solve the problem. Most of the time, you’ll only have to enter an App password once per app or device, so don’t worry about memorizing it.

https://support.google.com/accounts/answer/185833?hl=en

**Comment by vinnymac** [comment]
@AbeSchmidtMoz we currently do not support 2FA, but if you use a [AppPassword](https://security.google.com/settings/security/apppasswords) you can get in. This is how I am currently logging in. I might add a note about this to the ReadMe or app because it seems like a common complaint.

**Comment by AbeSchmidtMoz** [comment]
AppPassword worked, you rock , thanks!!!!!
