### ISSUE TITLE
White Screen on Load

### ISSUE THREAD

**Issue by vinnymac** [vinnymac/PokeNurse#45]
As the ReadMe states

> Sometimes after login, the page will stay white instead of showing the list of Pokemon

I have only seen this occur once, but it would be great if we could keep track of it and get to the bottom of why it happens.

**Comment by mackhankins** [comment]
I see a load dely sometimes and its' a white screen, but eventually it loads.  I've never been able to replicate this.  The only problem I can replicate is idle for 30 minutes and then trying to refresh.

**Comment by vinnymac** [comment]
I believe the commit above may be related. When telling the app to start with the options `show: false`, then waiting till the app is ready before calling `show`, the login page no longer appears white on load. You now see the login page and window simultaneously.

I am guessing this is happening when we press login. We tell it to show the `home.html` immediately but it isn't yet done drawing the html, and our JS hasn't been processed and executed, followed by more reflows, etc.

You can read more about this in the docs for [BrowserWindow](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#using-ready-to-show-event)

I think the best solution would be to stop loading a new html file. We can still resize the window, but Instead just replace the current DOM with the one that includes our table. Doing this should be easy once we have migrated to `React`. It also aligns us more with the design principles of a Single Page Application.

EDIT: I just added a change on the `react` branch where we no longer have multiple `html` files. This should prevent the issue. We don't have a reliable way of testing it, so we will have to wait and see when these changes land.

**Comment by vinnymac** [comment]
The changes that went out with v1.1.1 may have fixed some of white screen issues. I'll close this and wait on reports.
