### ISSUE TITLE
Notifications appear as Errors

### ISSUE THREAD

**Issue by asiansteev** [vinnymac/PokeNurse#46]
When transferring and evolving pokemon, when the process is complete, the notification window that appears is an error which makes it seem as if the action failed (they always seem to succeed).
This is on Windows 10.
![screenshot 1](https://cloud.githubusercontent.com/assets/20084/17480649/e1774968-5d46-11e6-93d8-1de1355f8bc8.png)

**Comment by vinnymac** [comment]
Thanks for the report. This should be easy to fix.

We just have to stop using `'error-message'` event for when they complete.
See [here](https://github.com/duhminick/PokeNurse/blob/master/main.js#L56)
