### ISSUE TITLE
When expanding certain pokemon, I get a DataTables warning

### ISSUE THREAD

**Issue by asiansteev** [vinnymac/PokeNurse#48]
The expand works, but I have to click through on a warning first. The warning reads:

```
DataTables warning: table id=92 - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3
```

I don't know if it's pokemon-specific. It happens for me on Weepinbell and Beedrill. I have to click through a few warnings each time. This is on Windows 10.
![screenshot 3](https://cloud.githubusercontent.com/assets/20084/17480763/7e7ad8f6-5d47-11e6-80ee-1a4ce1d6262f.png)
![screenshot 4](https://cloud.githubusercontent.com/assets/20084/17480766/8031306e-5d47-11e6-9772-31a685f92b17.png)

**Comment by asiansteev** [comment]
this is not an issue on OS X Yosemite 10.10.5
edit: yeah it is, see below

**Comment by mackhankins** [comment]
I'm going to try to replicate the issue when I get home today.  I believe it may be an issue with Electron and Windows 10, but I can't confirm that without some debugging.

**Comment by vinnymac** [comment]
We are attempting to replace the entire table with React, so I figure that will squash this bug since we will be dropping jQuery.DataTable.

**Comment by asiansteev** [comment]
jk, this is an issue on OSX, it just wasn't appearing on the same pokemon...
![screen shot 2016-08-09 at 10 19 08 am](https://cloud.githubusercontent.com/assets/20084/17519716/1a2b6058-5e1b-11e6-9cd6-1ebc0abc9d4f.png)
<img width="1012" alt="screen shot 2016-08-09 at 10 20 10 am" src="https://cloud.githubusercontent.com/assets/20084/17519719/1c5e8ca6-5e1b-11e6-802c-b28a94318a1e.png">
