### ISSUE TITLE
question does this log in with any location data?

### ISSUE THREAD

**Issue by russr123** [vinnymac/PokeNurse#49]
dont want it showing me jumping GPS points with use

**Comment by vinnymac** [comment]
@russr123 this project uses [pogobuf](https://github.com/cyraxx/pogobuf) in order to retrieve account data. We don't explicitly use any location data, but if you would like to look into it, that library is where I would start to verify it.

**Comment by mackhankins** [comment]
We're not using any calls that require a location to my knowledge, but you can poke around https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.client.js to see which ones do.   A lot of it is outside the scope of this application.
