### ISSUE TITLE
NPM Errors on ubuntu

### ISSUE THREAD

**Issue by 3of5-IQ** [vinnymac/PokeNurse#5]
Does it work better on one OS than another? Getting the same error messages on ubuntu. I'm not too good with nodejs or npm, but would love to contribute in other ways. Maybe documentation or something. Could you take a look at the screen and see if there are any suggestions on how I can get it up and running? Thanks.

![image](https://cloud.githubusercontent.com/assets/13574377/17278125/c144d7de-5709-11e6-9c06-a85a67e9916c.png)

**Comment by duhminick** [comment]
You need libgtk.  Try this: `sudo apt-get install libgtk2.0-0:i386`

http://askubuntu.com/questions/356605/ubuntu-64-bit-machinarium-error-while-loading-shared-libraries-libgtk-x11-2-0
