### ISSUE TITLE
2 Factor Authentication not working

### ISSUE THREAD

**Issue by mannydelrio** [vinnymac/PokeNurse#51]
When opening and logging in with my email and password its not doing anything after clicking the login button, I have tried running as admin , as well as compability with Windows 7

**Comment by mackhankins** [comment]
Are you logging in with Google and if so are you using Two Factor Auth?  Also, since it has to download the react developer tools you might try logging in a second time after killing the app.

**Comment by mannydelrio** [comment]
yea it looks like the Two Factor Auth was messing it up.

**Comment by mackhankins** [comment]
Google 2 Factor Authentication cannot be used. However you can use an AppPassword instead.  See the readme for known issues.

We like the AppPassword method cause you don't need a token every time which gets old quick.

**Comment by vinnymac** [comment]
I think since this keeps happening we are going to want to build something in the app that informs 2FA users to visit the [AppPassword](https://security.google.com/settings/security/apppasswords) page. We could use the current `error-message` mechanism for this maybe?
