### ISSUE TITLE
Teleportation problem?

### ISSUE THREAD

**Issue by rickycc** [vinnymac/PokeNurse#52]
Since the app is going to send data to Niantic's server. Will the location be difference from last known position of the user? This might cause a permanent ban as the are tightening spoofing problems.

**Comment by mackhankins** [comment]
We were talking about something similar in a closed issue.

https://github.com/duhminick/PokeNurse/issues/49

**Comment by vinnymac** [comment]
This question is more for [pogobuf](https://github.com/cyraxx/pogobuf). If you are concerned about location, I suggest opening an issue there.

Based on the [documentation](https://github.com/cyraxx/pogobuf/wiki/Usage#basic-usage) for `pogobuf` it looks like the client does allow for manipulation of the users location. Whether it manipulates your location on the requests we send has not been determined. If it is a requirement for authentication or any other request, then I would imagine it does have that affect.

**Comment by jplusc** [comment]
From the code at [https://github.com/cyraxx/pogobuf/blob/master/pogobuf/pogobuf.client.js] it mentions: 

 /**
     \* Sets the player's latitude and longitude.
     \* Note that this does not actually update the player location on the server, it only sets
     \* the location to be used in following API calls. To update the location on the server you
     \* probably want to call {@link #updatePlayer}.
     \* @param {number} latitude - The player's latitude
     \* @param {number} longitude - The player's longitude
     \* @param {number} [altitude=0] - The player's altitude
     */

So looks like a login does not update the location.

**Comment by vinnymac** [comment]
We might want to add a FAQ to the readme because closing this issue won't suffice.
