### ISSUE TITLE
Let us choose our own delay when evolving/transfering

### ISSUE THREAD

**Issue by jabberjabber** [vinnymac/PokeNurse#56]

**Comment by venounan** [comment]
It might also be useful if the program maybe set a range for it to be randomized within. I.E. use a random number generator to pick an interval between 10-12 seconds for pause between each action, so that it's not a uniform amount every time. Just a thought to make it seem more "human".

**Comment by mackhankins** [comment]
@venounan it already does that, but it's between 25-30.  It'd be cool to set the range

**Comment by furier** [comment]
Even better would be to specify a range of ms, like: 3000-6000 which should give good results and not whole seconds which could be suspicious. Say all transfers were exactly 1,2,3,4 or 5 seconds in duration in between that could indicate that it is not a human doing the transferring.

**Comment by vinnymac** [comment]
@furier there are other factors at play such as network connectivity and slowness, I highly doubt this concern will ever come into play. But feel free to do a pull request if you want that level of comfort.

EDIT: Also rate limiting is a thing, so even if we allowed you to control the time, it would have a lower boundary, at which point this feature becomes kind of useless.

**Comment by vinnymac** [comment]
This is not needed anymore because A) pogobuf already limits hammering the api, and B) batch calls are now used for transfer/evolve.
