### ISSUE TITLE
remove ability to transfer starred pokemon

### ISSUE THREAD

**Issue by asiansteev** [vinnymac/PokeNurse#58]
the official pokemon go app prevents you from transferring starred pokemon.
pokenurse allows you to transfer starred pokemon, which, especially with batch transfers, seems dangerous.
if we don't remove the ability to transfer starred pokemon, perhaps at least prompt a warning stating "You are about to transfer a starred pokemon, are you sure?" "Cancel/Transfer"

**Comment by mackhankins** [comment]
This has been tested and merged.
