### ISSUE TITLE
NPM error on debian

### ISSUE THREAD

**Issue by Carravan** [vinnymac/PokeNurse#6]
> pokenurse@1.0.0 start /var/www/PokeNurse
> electron .

npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v0.12.15
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! pokenurse@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pokenurse@1.0.0 start script 'electron .'.
npm ERR! This is most likely a problem with the pokenurse package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pokenurse
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls pokenurse
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /var/www/PokeNurse/npm-debug.log

Contents of npm-debug.log
  GNU nano 2.2.6                                                                 File: npm-debug.log

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.1
3 info using node@v0.12.15
4 verbose node symlink /usr/bin/node
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart pokenurse@1.0.0
7 info start pokenurse@1.0.0
8 verbose unsafe-perm in lifecycle true
9 info pokenurse@1.0.0 Failed to exec start script
10 verbose stack Error: pokenurse@1.0.0 start: `electron .`
10 verbose stack Exit status 1
10 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
10 verbose stack     at EventEmitter.emit (events.js:110:17)
10 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
10 verbose stack     at ChildProcess.emit (events.js:110:17)
10 verbose stack     at maybeClose (child_process.js:1019:16)
10 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1091:5)
11 verbose pkgid pokenurse@1.0.0
12 verbose cwd /var/www/PokeNurse
13 error Linux 3.16.0-4-amd64
14 error argv "/usr/bin/node" "/usr/bin/npm" "start"
15 error node v0.12.15
16 error npm  v2.15.1
17 error code ELIFECYCLE
18 error pokenurse@1.0.0 start: `electron .`
18 error Exit status 1
19 error Failed at the pokenurse@1.0.0 start script 'electron .'.
19 error This is most likely a problem with the pokenurse package,
19 error not with npm itself.
19 error Tell the author that this fails on your system:
19 error     electron .
19 error You can get information on how to open an issue for this project with:
19 error     npm bugs pokenurse
19 error Or if that isn't available, you can get their info via:
19 error
19 error     npm owner ls pokenurse
19 error There is likely additional logging output above.
20 verbose exit [ 1, true ]

**Comment by josephbedminster** [comment]
same here

**Comment by Carravan** [comment]
It might be the node version that is distributed with debian in the first place.

> 15 error node v0.12.15
> 16 error npm v2.15.1

I'm running Debian 8.5 jessie atm. Will try to update to a later node version and try again.

**Comment by duhminick** [comment]
I'm not quite sure what the problem could be.

If it helps at all these are the versions that I'm using on my machines.
Mac OS X: `npm 3.7.3, node v5.9.0`
Windows: `npm 2.4.12, node v4.2.6`
