### ISSUE TITLE
Do not "unselect" Pokemon after power up

### ISSUE THREAD

**Issue by adamlieb** [vinnymac/PokeNurse#60]
As a user I am trying to power up a Pokemon many times so I can evolve him. Each time I "complete" one power up, my viewport gets reset (if I have searched) and Pokemon dropdown (after I click the little plus) gets minimized. This creates multiple extra clicks for each upgrade. This eliminates part of the convenience of being able to upgrade from a desktop app.

**Comment by vinnymac** [comment]
We are well aware of this one. The entire table currently relies on a library called `jQuery.DataTable` and it is making it a lot harder to manage updating from new data. We are in the process of rewriting the table in `React`, and this issue will not be difficult to solve once that is completed.
