### ISSUE TITLE
White Screen

### ISSUE THREAD

**Issue by Neroxo** [vinnymac/PokeNurse#64]
Hi,
I need help. I'm still getting white screen. Can someone help me?

![white screen](https://cloud.githubusercontent.com/assets/20956097/17567606/604ec798-5f40-11e6-9973-64514c37649e.png)

I was trying, and trying, but i still got white screen.
Sorry for my English. Im from Poland.

**Comment by mackhankins** [comment]
If you're using 2FA with Google, then you need to use an [AppPassword](https://security.google.com/settings/security/apppasswords).  The next version has some better error handling for this.

**Comment by vinnymac** [comment]
Can you press Ctrl+Shift+I and tell us if you see a new window with red errors in it? If you do send us a screenshot of that window.

**Comment by Neroxo** [comment]
@mackhankins Im using PTC.
@vinnymac Nothing happen when i press Ctrl + Shift + I . Still white screen.

**Comment by Neroxo** [comment]
![output_qshcx7](https://cloud.githubusercontent.com/assets/20956097/17585430/fa72e7a2-5fbb-11e6-9647-8e4978ce2dc9.gif)

Here is gif how it looks. Everytime when i open PokeNurse there is white screen.

**Comment by Neroxo** [comment]
I downloaded 32 bit version and it worked! (I dont know why because i have 64 bit win version).

**Comment by vinnymac** [comment]
@Neroxo we just released v1.1.1 maybe you can try those versions too 👍
