### ISSUE TITLE
100% IV pokemon show up last

### ISSUE THREAD

**Issue by venounan** [vinnymac/PokeNurse#67]
100% IV pokemon show up at the bottom of the list when sorting by IV, instead of the top. 
![screen shot 2016-08-10 at 5 12 02 pm](https://cloud.githubusercontent.com/assets/20630800/17571276/954b2716-5f1d-11e6-87cc-d13aa651d9ab.png)

**Comment by d-bischoff** [comment]
Also single digits have that bug. 
9 > 89 > 88 > 87

**Comment by vinnymac** [comment]
We are reimplementing sorting ourselves instead of relying on a third party library (jQuery.DataTable) in the React branch, so that will give us more control over these issues.
