### ISSUE TITLE
wrong pokemon detail when clicked

### ISSUE THREAD

**Issue by WilliamAnthony** [vinnymac/PokeNurse#68]
No matter which pokemon I clicked, the detail always show bulbasaur (or maybe the smallest pokedex I've got)

**Comment by mackhankins** [comment]
Could I have an image of that?  The error doesn't sound like anything we've had before....

**Comment by WilliamAnthony** [comment]
After I login, it shows the pokemon list -- https://s10.postimg.org/a8dmnm6w7/list.jpg
Tried to click Pinsir (the first one) or other, always showing Bulbasaur -- https://s10.postimg.org/eisaj7bzb/popup.jpg

**Comment by vinnymac** [comment]
@WilliamAnthony Which version of the app are you using? Did you compile it yourself?
The table in your screenshot doesn't show the expand buttons and is outdated or broken.
