### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by vinsilsim** [vinnymac/PokeNurse#70]
Please help me with error:

> pokenurse@1.1.0 start /home/PokeNurse
> electron .

/home/PokeNurse/node_modules/electron-prebuilt/dist/electron: error while loading shared libraries: libgtk-x11-2.0.so.0: cannot open shared object file: No such file or directory
npm ERR! weird error 127
npm ERR! not ok code 0

**Comment by mackhankins** [comment]
What's yourOS?  I don't recognize the error..  What's your node version?

**Comment by WilliamAnthony** [comment]
Sorry I replied to this thread.
@mackhankins  it's Linux, same as mine.
@vinsilsim have you tried to install libgtk2.0-0:i386 package?

**Comment by vinsilsim** [comment]
@WilliamAnthony yes i install libgtk2.0-0:i386! not work =/

**Comment by mackhankins** [comment]
We're going to add a Linux compile soon I think.  Checking into that this morning.

**Comment by vinnymac** [comment]
@vinsilsim Linux builds are now available for trying

https://github.com/duhminick/PokeNurse/releases

**Comment by vinsilsim** [comment]
@vinnymac thank you!
