### ISSUE TITLE
Renaming

### ISSUE THREAD

**Issue by khag7** [vinnymac/PokeNurse#72]
I like to have the IV in the nickname. Some people like even more complex naming involving moveset and attack/defense stats. It would be really nice to have a place where you could type in the template, then check boxes next to some of your 'mons and click "rename by template" and they all get a new name.

Template like this:
`[IV]_[ATT]/[DEF]/[STA]`
would produce names like:
80_13/12/12

And of course manual renaming should be allowed as well. But templating makes batch renaming possible.

I take the simpler route, myself, of:
99_Dragonite

**Comment by vinnymac** [comment]
This honestly would be very low priority unless someone made a great pull request. We would certainly add renaming before adding templated renaming. Interesting idea though, curious how many others want this.

**Comment by khag7** [comment]
I think definitely renaming manually would come first.

There are always people posting on reddit about their unique naming scheme, but like you said, it depends on how many users here want it.

Also I used to use this tool to put IV's in my names, not sure if it still works though:
http://www.ownedcore.com/forums/pokemon-go/pokemon-go-hacks-cheats/564278-ivy-pokemon-batch-renamer-show-pokemon-iv-perfection-their-nickname.html

**Comment by mackhankins** [comment]
I like the feature idea honestly, but on a short hold until we knock out some stuff.  Manual renaming first obviously...

**Comment by xymor** [comment]
This is really nice and super easy to do, 3 lines to call the pogobuf api.

**Comment by khag7** [comment]
I've been using that Ivy exe I linked above. The dev of that program said basically the same thing, its ridiculously simple commands. I'm not too familiar with using the pogobuf api but I've been playing around with it. Maybe I'll make that my first PR here.

**Comment by vinnymac** [comment]
We are almost done with v1.2 and then renaming will be easy to add.
The [call to the API](https://github.com/cyraxx/pogobuf/wiki/pogobuf.Client-Pok%C3%A9mon-Go-API-Methods#nicknamepokemonpokemonid-nickname--promise) is the easiest part. Updating the data for that individual nickname will be the hardest part for whoever is unfamiliar with the project. Then later maybe we will add the templating feature, that would be a good PR.
