### ISSUE TITLE
Does not open with MAC OSX.

### ISSUE THREAD

**Issue by breinntaguilar** [vinnymac/PokeNurse#73]
It says cannot open application because of unidentified author.

**Comment by mackhankins** [comment]
Right click and select open.  You only have to do this once.

**Comment by vinnymac** [comment]
Please provide the version you are using as well as the version of your operating system. Make sure you can open unsigned applications, this is not signed.

**Comment by breinntaguilar** [comment]
OS X El Capitan
Version 10.11.5

@vinnymac what should i do to open unsigned application in OSX? sorry for the noob question.
![screen shot 2016-08-11 at 8 15 57 pm](https://cloud.githubusercontent.com/assets/2063011/17588300/74bf2a7c-6000-11e6-88a6-14b00bde23e5.png)

**Comment by breinntaguilar** [comment]
Was able to open it but this happened. See screenshot.
![screen shot 2016-08-11 at 8 17 32 pm](https://cloud.githubusercontent.com/assets/2063011/17588337/babaa6e6-6000-11e6-97b8-340b24bf82f3.png)

**Comment by breinntaguilar** [comment]
I was logging in using GMAIL email. Logging in using the PTC is working though. :)

**Comment by furier** [comment]
Do you use two factor auth for google? that may be the issue...

**Comment by vinnymac** [comment]
@breinntaguilar I have never seen that particular error before. It does not look related to 2FA to me. However, we have received reports of flaky/proxy/VPN connections having issues. That particular error is an error in the TLS Socket handler for the http node lib. I recommend trying a different connection if you want to use google.

**Comment by breinntaguilar** [comment]
Alright. Thanks @vinnymac for the help! 👍

**Comment by breinntaguilar** [comment]
Thanks @furier too. :)
