### ISSUE TITLE
Table Styles

### ISSUE THREAD

**Issue by AnarkhiA** [vinnymac/PokeNurse#83]
Hey, I don't mind the table that much, but maybe could you alternate between white and a grey color? it makes reading past the vast spaces more practical.

Maybe shorten those spaces too? 

Greets,
AnarkhiA

P.S. Love the programm!

**Comment by mackhankins** [comment]
I've tried this on what we call the species table (master table) and it looks horrible.  I think it looks okay on the pokemon table (sub-table).

One of the next versions has sprites on the species table which really helps.

![screen shot 2016-08-12 at 8 43 53 am](https://cloud.githubusercontent.com/assets/2184080/17624132/fedf0ed0-6068-11e6-8cdc-3c32f4feca13.png)

**Comment by AnarkhiA** [comment]
Ohh fast reply, thanks. I think its helpful to have it on the sub-table, and the sprites sure help alot too. 

Keep up the good work and I'll wait patiently for the next version.

Greets,
AnarkhiA

**Comment by mackhankins** [comment]
@AnarkhiA I think you'll see sprites when #76 is finished.  I don't think it'll be the next version, but it's coming.

Thanks :)

**Comment by vinnymac** [comment]
@AnarkhiA v1.1.1 is out 👍
