### ISSUE TITLE
Cannot sign in using pokemon trainer's club account

### ISSUE THREAD

**Issue by SomethingRndm** [vinnymac/PokeNurse#88]
Not sure if anyone else having the same problem, but get that google 403 login error message coming up.

**Comment by vinnymac** [comment]
@SomethingRndm you get a google error on PTC login? That doesn't sound right. The two are unrelated so maybe the toggle is broken, and it is using the google login?

**Comment by SomethingRndm** [comment]
yh, I think that may be the case... any idea when it will be fixed? (i'm not a developer, just a user in need of help lol)

**Comment by vinnymac** [comment]
@SomethingRndm just a quick question, did you click PokemonTrainerClub as the account type before you logged in?

**Comment by vinnymac** [comment]
Yea I just checked, it is now always google being used. Thanks for the report!

**Comment by mackhankins** [comment]
This fix has been merged into master.  Should be compiled soon for version 1.1.2
