### ISSUE TITLE
Inconvenient sorting

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#90]
In the new 1.1.1 version, when you expand a species, pokemon are no longer sorted by CP like in the previous version, they now are sorted by nickname by default.

**Comment by mackhankins** [comment]
I meant to fix this earlier.  1.1.2 should be out before the end of the night to correct some other mistakes I made.

**Comment by iPaulis** [comment]
I'm happy to see the development flows. Thank you for your work and dedication.
