### ISSUE TITLE
devDependencies included in releases

### ISSUE THREAD

**Issue by iPaulis** [vinnymac/PokeNurse#92]
Windows defender found this trojan in the new build 1.1.2: https://www.microsoft.com/security/portal/threat/encyclopedia/entry.aspx?name=Trojan%3aWin32%2fVarpes.M!cl&threatid=2147708972&enterprise=0

The infected file was: \UserFolder\PokeNurse-win32-x64\resources\app\node_modules\rcedit\bin\rcedit.exe

**Comment by vinnymac** [comment]
RCEdit.exe is a required file for windows builds. It allows modifications of executables when `electron-packager` builds the app. It may be possible for us to package the app without electron-packager, but that is currently the easiest way to do it, as NPM v3 flattens package dependencies. We should try excluding them if we can. Perhaps we should just use a separate package.json for development to prevent them from going into releases.

https://github.com/electron-userland/electron-packager/issues/53

EDIT: New build system on develop fixes this issue
