### ISSUE TITLE
Finer grain IV (reopened)

### ISSUE THREAD

**Issue by SteinerKD** [vinnymac/PokeNurse#93]
OK, been in contact with the Pogobuf creator and he suggested a slight change of code to get the decimal value return on IV values. This is what he said.

Take this code from line 233

`var percent = (att + def + stam) / 45 * 100;`

And change to:

`var percent = Math.round((att + def + stam) / 45 * 10000) / 100;`

For me as a mathematician it makes no sense as the output would be the same, but I guess the math.round function is the key here.

Looking around at other tools one decimal IV values is definitely the norm used everywhere, so would be nice for better comparison.

**Comment by mackhankins** [comment]
<img width="428" alt="screen shot 2016-08-13 at 8 26 42 am" src="https://cloud.githubusercontent.com/assets/2184080/17643432/bfc9707e-612f-11e6-8c18-43368c33d049.png">

I think I'd rather have just one decimal, but that's the results of the above.

**Comment by SteinerKD** [comment]
Wild guess, multiply by 1000 and divide by 10 instead? I agree, a single decimal is preferred. Maybe the docs for Math.round have a clue?

**Comment by mackhankins** [comment]
Final result is 93.3%.  Tested and merged.

**Comment by SteinerKD** [comment]
Awesome! 
Thank you.
