### ISSUE TITLE
Support for Google auth token

### ISSUE THREAD

**Issue by ferazambuja** [vinnymac/PokeNurse#95]
My google account doesn't' support AppPassword. A lot of the services use the token auth.
Would that be possible with this project?

**Comment by mackhankins** [comment]
I'm not going to say never, but it isn't part of any planned release.  I've never heard of a google account that does support appPassword though.  It's so much more convenient than tokens.

PR are welcome.

**Comment by ferazambuja** [comment]
My main account is from my university that's why doesn't support.
![screen shot 3](https://cloud.githubusercontent.com/assets/12782082/17646033/7bb3cf36-6186-11e6-831e-97df2fe49897.png)

**Comment by vinnymac** [comment]
@ferazambuja if you want this feature you're going to need to ask for it in the pogobuf repository and not here. We rely on pogobuf for all client interactions including authentication.
